{% set name = "openmim" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openmim-{{ version }}.tar.gz
  sha256: 42758b68fa6288bea5e70f0ef63b8c872f1d620b5e4e43c52d93dac54e70fb2e

build:
  entry_points:
    - mim = mim.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - click
    - colorama
    - model-index
    - pandas
    - pip >=19.3
    - requests
    - rich
    - tabulate

test:
  imports:
    - mim
  commands:
    - pip check
    - mim --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-mmlab/mim
  summary: MIM Installs OpenMMLab packages
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zhouzaida
    - giswqs
